# Generated by Django 2.2.4 on 2019-08-03 16:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mid', models.IntegerField(default=0)),
                ('belongs_to_collection', models.CharField(default=' ', max_length=50000)),
                ('budget', models.IntegerField(default=0)),
                ('genres', models.CharField(default=' ', max_length=50000)),
                ('homepage', models.CharField(default=' ', max_length=50000)),
                ('imdb_id', models.CharField(default=' ', max_length=5000)),
                ('original_language', models.CharField(default=' ', max_length=50000)),
                ('original_title', models.CharField(default=' ', max_length=50000)),
                ('overview', models.CharField(default=' ', max_length=50000)),
                ('popularity', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('poster_path', models.CharField(default=' ', max_length=50000)),
                ('production_companies', models.CharField(default=' ', max_length=50000)),
                ('production_countries', models.CharField(default=' ', max_length=50000)),
                ('release_date', models.DateField(default=django.utils.timezone.now)),
                ('runtime', models.IntegerField(default=0)),
                ('spoken_languages', models.CharField(default=' ', max_length=50000)),
                ('status', models.CharField(default=' ', max_length=50000)),
                ('tagline', models.CharField(default=' ', max_length=50000)),
                ('title', models.CharField(default=' ', max_length=50000)),
                ('Keywords', models.CharField(default=' ', max_length=50000)),
                ('cast', models.CharField(default=' ', max_length=50000)),
                ('crew', models.CharField(default=' ', max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name='MovieApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('rating', models.CharField(max_length=6)),
                ('genre', models.CharField(max_length=300)),
                ('image', models.TextField(blank=True)),
                ('tag', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movie.MovieApi')),
            ],
        ),
    ]
