# Generated by Django 2.0 on 2019-07-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=2)),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
    ]
