# Generated by Django 2.2.4 on 2019-08-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20190803_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.TextField(default=''),
        ),
    ]
