# Generated by Django 2.0 on 2019-07-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movieapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieapi',
            name='genre',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='movieapi',
            name='rating',
            field=models.CharField(max_length=6),
        ),
    ]
