# Generated by Django 2.2.4 on 2019-08-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20190803_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Mid',
            field=models.CharField(default=' ', max_length=50000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.CharField(default=' ', max_length=50000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.CharField(default=' ', max_length=50000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.CharField(default=' ', max_length=50000),
        ),
    ]
