# Generated by Django 2.0 on 2019-07-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_movieapi_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieapi',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movieapi',
            name='tag',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movieapi',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
