# Generated by Django 2.2.4 on 2019-08-03 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20190803_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Mid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.TextField(default=''),
        ),
    ]
