# Generated by Django 2.2.4 on 2019-08-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20190803_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='revenue',
            field=models.IntegerField(default=0),
        ),
    ]
