# Generated by Django 2.2.4 on 2019-08-05 00:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_movie_revenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mid', models.IntegerField(default=0)),
                ('belongs_to_collection', models.CharField(default=' ', max_length=50000)),
                ('budget', models.IntegerField(default=0)),
                ('genres', models.CharField(default=' ', max_length=50000)),
                ('homepage', models.CharField(default=' ', max_length=50000)),
                ('imdb_id', models.CharField(default=' ', max_length=5000)),
                ('original_language', models.CharField(default=' ', max_length=50000)),
                ('original_title', models.CharField(default=' ', max_length=50000)),
                ('overview', models.CharField(default=' ', max_length=50000)),
                ('popularity', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('poster_path', models.CharField(default=' ', max_length=50000)),
                ('production_companies', models.CharField(default=' ', max_length=50000)),
                ('production_countries', models.CharField(default=' ', max_length=50000)),
                ('release_date', models.DateField(default=django.utils.timezone.now)),
                ('runtime', models.TextField(default='')),
                ('spoken_languages', models.CharField(default=' ', max_length=50000)),
                ('status', models.CharField(default=' ', max_length=50000)),
                ('tagline', models.CharField(default=' ', max_length=50000)),
                ('title', models.CharField(default=' ', max_length=50000)),
                ('Keywords', models.CharField(default=' ', max_length=50000)),
                ('cast', models.CharField(default=' ', max_length=50000)),
                ('crew', models.CharField(default=' ', max_length=50000)),
            ],
        ),
        migrations.RenameModel(
            old_name='Movie',
            new_name='MovieTrain',
        ),
    ]
