# Generated by Django 2.2.4 on 2019-08-05 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20190805_0100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='MovieTest',
        ),
    ]
